const defaultFloors = [
        {
          id:'lg', name:'Lower Ground Floor', open:true,
          topLots:[
            {id:'LG-A',status:'occupied'},
            {id:'LG-B',status:'available'},
            {id:'LG-C',status:'occupied'},
            {id:'LG-D',status:'available'},
            {id:'D-LG-1',status:'disabled'},
            {id:'ENTRANCE',status:'entrance'},
            {id:'D-LG-2',status:'disabled'},
            {id:'LG-E',status:'occupied'},
            {id:'LG-F',status:'occupied'},
          ],
          bottomLots:[
            {id:'LG-M',status:'occupied'},
            {id:'LG-L',status:'available'},
            {id:'LG-K',status:'occupied'},
            {id:'LG-J',status:'available'},
            {id:'LG-I',status:'occupied'},
            {id:'LG-H',status:'occupied'},
            {id:'LG-G',status:'available'},
          ],
        },
        {
          id:'gf', name:'Ground Floor', open:false,
          // GF: top slopes are absolute boxes, top-lots spans full width
          // Bottom has no slopes, has IN/OUT label on left
          topLots:[
            {id:'GF-A',status:'occupied'},
            {id:'GF-B',status:'available'},
            {id:'D-GF-1',status:'disabled'},
            {id:'ENTRANCE',status:'entrance'},
            {id:'D-GF-2',status:'disabled'},
            {id:'GF-C',status:'occupied'},
            {id:'GF-D',status:'available'},
          ],
          bottomLots:[
            {id:'GF-K',status:'occupied'},
            {id:'GF-J',status:'available'},
            {id:'GF-I',status:'occupied'},
            {id:'GF-H',status:'available'},
            {id:'GF-G',status:'occupied'},
            {id:'GF-F',status:'occupied'},
            {id:'GF-E',status:'available'},
          ],
        },
        {
          id:'l1', name:'First Floor', open:false,
          topLots:[
            {id:'HATCH',status:'hatch'},
            {id:'L1-A',status:'available'},
            {id:'L1-B',status:'occupied'},
            {id:'D-L1-1',status:'disabled'},
            {id:'ENTRANCE',status:'entrance'},
            {id:'D-L1-2',status:'disabled'},
            {id:'L1-C',status:'available'},
            {id:'L1-D',status:'occupied'},
          ],
          bottomLots:[
            {id:'L1-E',status:'available'},
            {id:'L1-F',status:'available'},
            {id:'L1-G',status:'occupied'},
            {id:'L1-H',status:'available'},
            {id:'L1-I',status:'occupied'},
            {id:'L1-J',status:'available'},
            {id:'L1-K',status:'occupied'},
          ],
        },
        {
          id:'l2', name:'Second Floor', open:false,
          topLots:[
            {id:'HATCH',status:'hatch'},
            {id:'L2-A',status:'available'},
            {id:'L2-B',status:'occupied'},
            {id:'L2-C',status:'available'},
            {id:'L2-D',status:'occupied'},
            {id:'STAIRS',status:'stairs-box'},
            {id:'L2-E',status:'available'},
            {id:'L2-F',status:'occupied'},
            {id:'L2-G',status:'available'},
          ],
          bottomLots:[
            {id:'L2-H',status:'occupied'},
            {id:'L2-I',status:'occupied'},
            {id:'L2-J',status:'available'},
            {id:'L2-K',status:'occupied'},
            {id:'L2-L',status:'available'},
            {id:'L2-M',status:'occupied'},
            {id:'L2-N',status:'occupied'},
          ],
        },
        {
          id:'l3', name:'Third Floor', open:false,
          topLots:[
            {id:'L3-A',status:'available'},
            {id:'L3-B',status:'occupied'},
            {id:'L3-C',status:'available'},
            {id:'L3-D',status:'occupied'},
            {id:'L3-E',status:'available'},
            {id:'LIFT', status:'lift-box'},
            {id:'L3-F',status:'occupied'},
            {id:'L3-G',status:'available'},
            {id:'L3-H',status:'occupied'},
          ],
          bottomLots:[
            {id:'L3-I', status:'available'},
            {id:'L3-J', status:'occupied'},
            {id:'L3-K', status:'available'},
            {id:'L3-L', status:'occupied'},
            {id:'L3-M', status:'available'},
            {id:'L3-N', status:'available'},
            {id:'L3-O', status:'occupied'},
          ],
        },
];
