const defaultFloors = [
  {
    // LG Floor
    id: "lg",
    name: "Lower Ground Floor",
    open: true,
    topLots: [
      { id: "LG-A", status: "available" },
      { id: "LG-B", status: "available" },
      { id: "LG-C", status: "available" },
      { id: "LG-D", status: "available" },
      { id: "D-LG-1", status: "disabled" },
      { id: "ENTRANCE", status: "entrance" },
      { id: "D-LG-2", status: "disabled" },
      { id: "LG-E", status: "available" },
      { id: "LG-F", status: "available" },
    ],
    // LG Floor Bottom Lots
    bottomLots: [
      { id: "LG-M", status: "available" },
      { id: "LG-L", status: "available" },
      { id: "LG-K", status: "available" },
      { id: "LG-J", status: "available" },
      { id: "LG-I", status: "available" },
      { id: "LG-H", status: "available" },
      { id: "LG-G", status: "available" },
    ],
  },
  {
    // Ground Floor
    id: "gf",
    name: "Ground Floor",
    open: false,
    topLots: [
      { id: "GF-A", status: "available" },
      { id: "GF-B", status: "available" },
      { id: "D-GF-1", status: "disabled" },
      { id: "ENTRANCE", status: "entrance" },
      { id: "D-GF-2", status: "disabled" },
      { id: "GF-C", status: "available" },
      { id: "GF-D", status: "available" },
    ],
    bottomLots: [
      { id: "GF-K", status: "available" },
      { id: "GF-J", status: "available" },
      { id: "GF-I", status: "available" },
      { id: "GF-H", status: "available" },
      { id: "GF-G", status: "available" },
      { id: "GF-F", status: "available" },
      { id: "GF-E", status: "available" },
    ],
  },
  {
    id: "l1",
    name: "First Floor",
    open: false,
    topLots: [
      { id: "HATCH", status: "hatch" },
      { id: "L1-A", status: "available" },
      { id: "L1-B", status: "available" },
      { id: "D-L1-1", status: "disabled" },
      { id: "ENTRANCE", status: "entrance" },
      { id: "D-L1-2", status: "disabled" },
      { id: "L1-C", status: "available" },
      { id: "L1-D", status: "available" },
    ],
    bottomLots: [
      { id: "L1-E", status: "available" },
      { id: "L1-F", status: "available" },
      { id: "L1-G", status: "available" },
      { id: "L1-H", status: "available" },
      { id: "L1-I", status: "available" },
      { id: "L1-J", status: "available" },
      { id: "L1-K", status: "available" },
    ],
  },
  {
    id: "l2",
    name: "Second Floor",
    open: false,
    topLots: [
      { id: "HATCH", status: "hatch" },
      { id: "L2-A", status: "available" },
      { id: "L2-B", status: "available" },
      { id: "L2-C", status: "available" },
      { id: "L2-D", status: "available" },
      { id: "STAIRS", status: "stairs-box" },
      { id: "L2-E", status: "available" },
      { id: "L2-F", status: "available" },
      { id: "L2-G", status: "available" },
    ],
    bottomLots: [
      { id: "L2-H", status: "available" },
      { id: "L2-I", status: "available" },
      { id: "L2-J", status: "available" },
      { id: "L2-K", status: "available" },
      { id: "L2-L", status: "available" },
      { id: "L2-M", status: "available" },
      { id: "L2-N", status: "available" },
    ],
  },
  {
    id: "l3",
    name: "Third Floor",
    open: false,
    topLots: [
      { id: "L3-A", status: "available" },
      { id: "L3-B", status: "available" },
      { id: "L3-C", status: "available" },
      { id: "L3-D", status: "available" },
      { id: "L3-E", status: "available" },
      { id: "LIFT", status: "lift-box" },
      { id: "L3-F", status: "available" },
      { id: "L3-G", status: "available" },
      { id: "L3-H", status: "available" },
    ],
    bottomLots: [
      { id: "L3-I", status: "available" },
      { id: "L3-J", status: "available" },
      { id: "L3-K", status: "available" },
      { id: "L3-L", status: "available" },
      { id: "L3-M", status: "available" },
      { id: "L3-N", status: "available" },
      { id: "L3-O", status: "available" },
    ],
  },
];
